@echo off
@chcp 65001 > nul
setlocal enabledelayedexpansion

@REM 현재 배치 파일이 있는 디렉터리 (scripts 폴더)
set "SCRIPT_DIR=%~dp0"
@REM 상위 폴더 절대 경로
for %%A in ("%SCRIPT_DIR%\..") do set "PARENT_DIR=%%~fA"
@REM 헤더 파일 절대 경로
set "FILE=%PARENT_DIR%\BuildInfo.hpp"
@REM 오늘 날짜 (yyyy-MM-dd)
for /f %%i in ('powershell -command "Get-Date -Format yyyy-MM-dd"') do set "BUILD_DATE=%%i"
@REM 빌드 시간 (HH:mm:ss)
for /f %%i in ('powershell -command "Get-Date -Format HH:mm:ss"') do set "BUILD_TIME=%%i"

@REM 헤더 파일 없으면 생성
if not exist "%FILE%" (
    (
        echo // Auto-generated Build Info
        echo // Do not modify manually
        echo #pragma once
        echo #define BUILD_NUMBER 0
        echo #define BUILD_DATE L"!BUILD_DATE!"
    ) > "%FILE%"
)
@REM 기존 BUILD_NUMBER 파싱
set "BUILD_NUM="
for /f "tokens=3" %%A in ('findstr /B /C:"#define BUILD_NUMBER" "%FILE%"') do set "BUILD_NUM=%%A"
@REM 값이 없으면 0으로 초기화
if not defined BUILD_NUM set "BUILD_NUM=0"
@REM 증가
set /a BUILD_NUM+=1
@REM 헤더 재작성
(
    echo // This file was automatically generated by BuildInfo.bat
    echo // Generated on %BUILD_DATE% %BUILD_TIME%
    echo // Do not modify manually
    echo.
    echo #pragma once
    echo.
    echo #define BUILD_NUMBER !BUILD_NUM!
    echo #define BUILD_DATE L"!BUILD_DATE!"
    echo.
) > "%FILE%"

endlocal