// This file was automatically generated by BuildInfo.bat
// Generated on 2025-06-13 21:33:46
// Do not modify manually

#pragma once

#define BUILD_NUMBER 588
#define BUILD_DATE L"2025-06-13"

