// This file was automatically generated by BuildInfo.bat
// Generated on 2025-06-14 16:40:00
// Do not modify manually

#pragma once

#define BUILD_NUMBER 611
#define BUILD_DATE L"2025-06-14"

