// This file was automatically generated by BuildInfo.bat
// Generated on 2025-06-08 01:05:17
// Do not modify manually

#pragma once

#define BUILD_NUMBER 319
#define BUILD_DATE L"2025-06-08"

